apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: exec
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: exec
  minReplicas: 5
  maxReplicas: 17
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 62
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 62
